### ISSUE TITLE
Is this project in use by anyone?

### ISSUE THREAD

**Issue by mrbobbytables** [pmorie/go-open-service-broker-client#172]
At this time, the kubernetes project is considering archiving this project. It may still be forked and maintained externally, however there does not appear to be enough momentum in project to keep it going.

If you are a user of this project, please chime in on this thread.

**Comment by danicat** [comment]
@mrbobbytables I am currently exploring the possibility of using this project. I'm not familiar with k8s community procedures for archival, but considering the merged PR above, should I assume a decision has been made to archive it?

**Comment by mrbobbytables** [comment]
@danicat yup, the repos will be archived. People will be free to fork and maintain their own copy and if an authoritative fork pops up we can update descriptions pointing to it 👍

**Comment by danicat** [comment]
Thanks for the clarification!

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
