### ISSUE TITLE
Deprovision fails due to missing query params

### ISSUE THREAD

**Issue by robertgmoss** [pmorie/go-open-service-broker-client#51]
In [deprovision_instance.go](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/deprovision_instance.go) it appears that what should be query params according to the OSB spec on [deprovisioning](https://github.com/openservicebrokerapi/servicebroker/blob/v2.12/spec.md#deprovisioning) are being sent as body to the `DELETE`.

**Comment by duglin** [comment]
It appears that service and plan are in the body ( https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/deprovision_instance.go#L27 ) and not in the query params per the spec ( https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#parameters-4 ).

**Comment by pmorie** [comment]
@robertgmoss following up - did @duglin's comments clarify things for you?  May I ask what broker is affected by this?

**Comment by robertgmoss** [comment]
@pmorie I believe @duglin was pointing out where in the code the spec has been interpreted incorrectly.  This should affect all brokers.  But in my case the [Apache Brooklyn Service Broker](https://github.com/cloudfoundry-incubator/apache-brooklyn-service-broker) which uses this [spring cloud project](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker)

**Comment by pmorie** [comment]
Yeah, this is a bug.  @staebler, you've got this one.
