### ISSUE TITLE
v2.ProvisionResponse and provisionSuccessResponseBody should use the same json field names

### ISSUE THREAD

**Issue by khatribharat** [pmorie/go-open-service-broker-client#91]
[`v2.ProvisionResponse`](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/types.go#L183) uses json field name `operationKey` [here](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/types.go#L192) and [`provisionSuccessResponseBody`](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/provision_instance.go#L21) uses json field name `operation` [here](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/provision_instance.go#L23).

`v2.ProvisionResponse` could be directly serialized and fed into `v2.Client` if the json fields b/w client and server match.

**Comment by pmorie** [comment]
@khatribharat that sounds like an awesome idea. Sorry to take so long to respond on this - January has been crazy and my gh notifications are out of control.

Is your use-case for this implementing a broker that uses this client library? cc @LiliC

**Comment by khatribharat** [comment]
yes, you're right. I'm using the client library in a broker implementation.
