### ISSUE TITLE
Change binding_retrievable to bindingRetrievable

### ISSUE THREAD

**Issue by jpeeler** [pmorie/go-open-service-broker-client#93]
This is to be consistent with the upcoming changes in service-catalog.

**Comment by pmorie** [comment]
This should match the OSB spec - what is the name of the field in the spec?

**Comment by jpeeler** [comment]
It looks like it's "bindings_retrievable" actually.

**Comment by pmorie** [comment]
K, so client is fine and shoud not change

**Comment by jpeeler** [comment]
I'll close this, but binding vs bindings is slightly different.

**Comment by kibbles-n-bytes** [comment]
@jpeeler @pmorie Huh, looks like the GET draft changed the field name... It totally was `binding_retrievable` before (Proof below to prove I'm not crazy). We will need to update this to handle the changed field name, then. ![binding_retrievable](https://user-images.githubusercontent.com/4024724/35586962-2a1a88a6-05b1-11e8-952c-265e23b82a24.png)
