### ISSUE TITLE
Library should support previous_values in UpdateInstanceRequest

### ISSUE THREAD

**Issue by girikuncoro** [pmorie/go-open-service-broker-client#94]
I'm currently using this library to build a component that's talking to [on demand service broker](https://github.com/pivotal-cf/on-demand-service-broker). As written in the comment, the library is missing `previous_values` field in `UpdateInstanceRequest` [here](https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/types.go#L228)

This is important missing piece for me because the broker I talk to requires `previous_values` for updating service instance which is according to the [spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#updating-a-service-instance). Specifically the broker will look for `previous_values` [here](https://github.com/pivotal-cf/on-demand-service-broker/blob/master/broker/update.go#L52) which is currently empty since the library is not passing it on.

If you are ok, I can make a PR for this.

cc @frodenas

**Comment by pmorie** [comment]
I’m happy to accept a PR for this.

**Comment by pmorie** [comment]
Closed by #95
